version: "3.8"

services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    profiles: ["prod"]
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - bot_network

  bot-dev:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./bot:/app/bot
      - ./alembic:/app/alembic
      - ./main.py:/app/main.py
      - ./alembic.ini:/app/alembic.ini
      - ./data:/app/data
    command: python main.py
    profiles: ["dev"]
    networks:
      - bot_network

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    profiles: ["dev","prod"]
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    networks:
      - bot_network

volumes:
  redis_data:

networks:
  bot_network:
    driver: bridge