services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    # (Опционально) Проброс порта, если нужно подключаться к Redis с хост-машины напрямую (например, для отладки)
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: