"""empty message

Revision ID: 01b3b12d8cff
Revises: 9d87f0a24e71
Create Date: 2025-04-20 21:34:30.845953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b3b12d8cff'
down_revision: Union[str, None] = '9d87f0a24e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enable_public_questions', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enable_public_questions')
    # ### end Alembic commands ###
