"""empty message

Revision ID: 9d87f0a24e71
Revises: 45b63d77deda
Create Date: 2025-04-20 13:09:59.124970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9d87f0a24e71'
down_revision: Union[str, None] = '45b63d77deda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_questions',
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('answer_year', sa.Integer(), nullable=False),
                    sa.Column('answer_month', sa.Integer(), nullable=True),
                    sa.Column('answer_day', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_public_questions_id'), 'public_questions', ['id'], unique=False)
    op.create_table('public_answers',
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('type',
                              sa.Enum('CORRECT', 'PART', 'INCORRECT', name='answer_type_enum_public', native_enum=False,
                                      create_constraint=True), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=False),
                    sa.Column('month', sa.Integer(), nullable=True),
                    sa.Column('day', sa.Integer(), nullable=True),
                    sa.Column('question_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['question_id'], ['public_questions.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_public_answers_id'), 'public_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_answers_id'), table_name='public_answers')
    op.drop_table('public_answers')
    op.drop_index(op.f('ix_public_questions_id'), table_name='public_questions')
    op.drop_table('public_questions')
    # ### end Alembic commands ###
