answer_history_limit: 10
boost_answer_threshold: 10
boost_limit_factor: 10.0
max_weight_during_boost:  15.0
min_final_weight: 1.0

fight_waiting_player_timeout: 60
fight_round_answer_time: 20
fight_round_countdown_time: 5
fight_starting_health: 5000